/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        // Capital Intel Design System
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'primary-fixed': '#dae2fd',
        'on-tertiary-fixed-variant': '#574425',
        'inverse-on-surface': '#eff1f3',
        'surface-container': '#eceef0',
        'inverse-primary': '#bec6e0',
        'secondary-fixed': '#d5e3fd',
        'on-tertiary-container': '#98805d',
        'on-secondary-container': '#57657b',
        'tertiary-fixed': '#fcdeb5',
        'primary-container': '#131b2e',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#0d1c2f',
        'on-tertiary': '#ffffff',
        'surface': '#f7f9fb',
        'on-surface-variant': '#45464d',
        'outline': '#76777d',
        'primary': '#000000',
        'on-primary-fixed': '#131b2e',
        'tertiary': '#000000',
        'outline-variant': '#c6c6cd',
        'surface-container-high': '#e6e8ea',
        'on-surface': '#191c1e',
        'on-background': '#191c1e',
        'secondary-fixed-dim': '#b9c7e0',
        'primary-fixed-dim': '#bec6e0',
        'surface-container-highest': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'on-primary-container': '#7c839b',
        'inverse-surface': '#2d3133',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'secondary': '#515f74',
        'on-tertiary-fixed': '#271901',
        'surface-dim': '#d8dadc',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#dec29a',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#3a485c',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#565e74',
        'tertiary-container': '#271901',
        'on-primary-fixed-variant': '#3f465c',
        'surface-bright': '#f7f9fb',
        'background': '#f7f9fb',
        'secondary-container': '#d5e3fd',
        // Functional category colors
        'emergency': '#dc2626',
        'investment': '#eab308',
        'retirement': '#16a34a',
        'contingency': '#2563eb',
      },
      fontFamily: {
        'label-caps': ['Inter'],
        'data-display': ['Inter'],
        'table-data': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'mono-data': ['JetBrains Mono'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'data-display': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'table-data': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'mono-data': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '1rem',
        'stack-md': '1rem',
        'gutter': '1.5rem',
        'stack-lg': '2rem',
        'stack-sm': '0.5rem',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
